### ISSUE TITLE
On 'make up' new node gives error

### ISSUE THREAD

**Issue by syuan100** [chainpoint/chainpoint-node#37]
After i run `make up` this happens:

chainpoint-node_1  | 2017-09-20T01:40:27.508112915Z /home/node/app/lib/calendar.js:208
chainpoint-node_1  | 2017-09-20T01:40:27.508621043Z         { console.error('Could not read calendar block range ${ nextRangeNeededIndex }${ error.statusCode ? ': error ' + error.statusCode : '' } ...Retrying in 5 seconds...') }
chainpoint-node_1  | 2017-09-20T01:40:27.508663406Z                  ^
chainpoint-node_1  | 2017-09-20T01:40:27.508733345Z
chainpoint-node_1  | 2017-09-20T01:40:27.508745739Z SyntaxError: Unexpected token .
chainpoint-node_1  | 2017-09-20T01:40:27.508755705Z     at createScript (vm.js:74:10)
chainpoint-node_1  | 2017-09-20T01:40:27.508765349Z     at Object.runInThisContext (vm.js:116:10)
chainpoint-node_1  | 2017-09-20T01:40:27.508805484Z     at Module._compile (module.js:533:28)
chainpoint-node_1  | 2017-09-20T01:40:27.508820838Z     at Object.Module._extensions..js (module.js:580:10)
chainpoint-node_1  | 2017-09-20T01:40:27.508830954Z     at Module.load (module.js:503:32)
chainpoint-node_1  | 2017-09-20T01:40:27.508840688Z     at tryModuleLoad (module.js:466:12)
chainpoint-node_1  | 2017-09-20T01:40:27.508850941Z     at Function.Module._load (module.js:458:3)
chainpoint-node_1  | 2017-09-20T01:40:27.508861398Z     at Module.require (module.js:513:17)
chainpoint-node_1  | 2017-09-20T01:40:27.508927327Z     at require (internal/module.js:11:18)
chainpoint-node_1  | 2017-09-20T01:40:27.508939697Z     at Object.<anonymous> (/home/node/app/server.js:23:18)
chainpoint-node_1  | 2017-09-20T01:40:27.508963577Z     at Module._compile (module.js:569:30)
chainpoint-node_1  | 2017-09-20T01:40:27.509029282Z     at Object.Module._extensions..js (module.js:580:10)
chainpoint-node_1  | 2017-09-20T01:40:27.509041339Z     at Module.load (module.js:503:32)
chainpoint-node_1  | 2017-09-20T01:40:27.509051016Z     at tryModuleLoad (module.js:466:12)
chainpoint-node_1  | 2017-09-20T01:40:27.509060429Z     at Function.Module._load (module.js:458:3)
chainpoint-node_1  | 2017-09-20T01:40:27.509100808Z     at Function.Module.runMain (module.js:605:10)
chainpoint-node_1  | 2017-09-20T01:40:27.509115921Z     at startup (bootstrap_node.js:158:16)
chainpoint-node_1  | 2017-09-20T01:40:27.509898361Z     at bootstrap_node.js:575:3
chainpoint-node_1  | 2017-09-20T01:40:27.528094001Z error Command failed with exit code 1.

**Comment by syuan100** [comment]
Resolved with latest chainpoint node image update

**Comment by syuan100** [comment]
ref: https://github.com/chainpoint/chainpoint-node/commit/14ee2c98fcac20732131167ffdb901fb96abec0c
